name: 'Create Azure ML Workspace'
description: 'Create an Azure ML Workspace'
author: 'dciborow'
branding:
  icon: 'git-commit'
  color: 'green'
inputs: 
  subscription_id:
    description: 'Azure Subscription Id'
    required: true
  resource_group:
    description: 'Azure Resource Group Name'
    required: true
  workspace_name:
    description: 'Azure ML Workspace Name'
    required: true
  workspace_region:
    description: 'Azure ML Workspace Region'
    required: false
    default: 'westus'
runs:
  using: 'docker'
  image: 'Dockerfile'
